dist: xenial
language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"
- "pypy"
- "pypy3"

install:
- pip install -r requirements-devel.txt
- pip install coveralls pytest-cov

script:
- py.test test --cov anymarkup_core

after_success:
- coveralls
